name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.26'  # Adjust to your Go version
      
      - name: Build Windows executable
        run: |
          go build -o NetworkScanner.exe -v ./cmd/checker
        shell: pwsh
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: NetworkScanner.exe
          body: |
            # Запускать от имени администратора

            После запуска создает файл `network_checker_report.html` и открывает его в браузере для просмотра отчета.
            В случае, если браузер не открылся - следуйте инструкции ниже:

            1. Нажимаете сочетание клавиш `Win + R`
            2. Вставляете в открывшееся окно строку - `"C:\Users\%username%\AppData\Local\Temp\network_checker_report.html"`
            3. Нажимаете `Enter`

            # Важно!
            > Наличие обнаруженных настроек не гарантирует, что нужно забанить подозреваемого за них. Следует внимательно изучить, что именно настроено и какое значение выставлено для того или иного пункта
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
