name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.26'  # Adjust to your Go version
      
      - name: Build Windows executable
        run: |
          go build -o NetworkScanner.exe -v ./cmd/checker
        shell: pwsh
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: NetworkScanner.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
